version: '2'

services:

  packet-forwarder:
    image: "nebraltd/hm-pktfwd:b94564ccd3bef1fe2ecbf9725ad6416ff4c82e7d"
    privileged: true
    volumes:
      - 'pktfwdr:/var/pktfwd'

  helium-miner:
    image: "nebraltd/hm-miner:67e32cab671bd0af26f3c854d5f716b09b32c1e7"
    ports:
      - "44158:44158/tcp"
      - "1680:1680/udp"
    volumes:
      - 'miner-storage:/var/data'
      - 'miner-log:/var/log/miner'
      - 'pktfwdr:/var/pktfwd'
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    labels:
      io.balena.features.dbus: '1'
      # io.balena.features.sysfs: '1'
      # io.balena.features.kernel-modules: '1'

  gateway-config:
    image: "nebraltd/hm-config:0d2f2aba83f2ab4400e30ec04bd8f0ccb69307d0"
    privileged: true
    network_mode: "host"
    cap_add:
            - NET_ADMIN
    volumes:
      - 'miner-storage:/var/data'
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.sysfs: '1'
      io.balena.features.kernel-modules: '1'
      io.balena.features.supervisor-api: '1'
    stop_signal: SIGINT

  diagnostics:
    image: "nebraltd/hm-diag:86274f5df600071b64cca55a0bc2e56d30fb1f20"
    volumes:
      - 'pktfwdr:/var/pktfwd'
      - 'miner-storage:/var/data'
    ports:
      - '80:80'
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.sysfs: '1'

volumes:
  miner-storage:
  miner-log:
  pktfwdr:
