version: '2'

services:

  gateway-config:
    image: "nebraltd/hm-config:39c54b2eb0c412f4a84a3248019086c3a7fa2167"
    environment:
      - 'FIRMWARE_VERSION=2021.06.10.1'
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    privileged: true
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - 'miner-storage:/var/data'
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.sysfs: '1'
      io.balena.features.kernel-modules: '1'
      io.balena.features.supervisor-api: '1'
    stop_signal: SIGINT

  packet-forwarder:
    image: "nebraltd/hm-pktfwd:53ec9ad62e80aa596e1ade87a7f8395ae5130ec3"
    privileged: true
    volumes:
      - 'pktfwdr:/var/pktfwd'

  helium-miner:
    image: "nebraltd/hm-miner:014a421da13fabc17eadbaae56a0db1a4f2d349a"
    ports:
      - "44158:44158/tcp"
      - "1680:1680/udp"
    volumes:
      - 'miner-storage:/var/data'
      - 'miner-log:/var/log/miner'
      - 'pktfwdr:/var/pktfwd'
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    labels:
      io.balena.features.dbus: '1'
      # io.balena.features.sysfs: '1'
      # io.balena.features.kernel-modules: '1'

  diagnostics:
    image: "nebraltd/hm-diag:7e9e2bbbdd81b5ca7bd22f636ccc672b28cd39ac"
    environment:
      - 'FIRMWARE_VERSION=2021.06.10.1'
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    volumes:
      - 'pktfwdr:/var/pktfwd'
      - 'miner-storage:/var/data'
    ports:
      - '80:80'
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    labels:
      io.balena.features.sysfs: '1'
      io.balena.features.dbus: '1'

  gwmfr:
    image: "nebraltd/hm-gwmfr:68329fce90fa6ba5169c700d763fe941b7e414f4"
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    restart: on-failure

  upnp:
    image: "nebraltd/hm-upnp:64a5b7ba81b3ab7de37dc5dcd3f7d025a34b3410"
    network_mode: "host"
    restart: on-failure
    volumes:
      - 'pktfwdr:/var/pktfwd'

volumes:
  miner-storage:
  miner-log:
  pktfwdr:
