version: '2'

services:

  packet-forwarder:
    image: "nebraltd/hm-pktfwd:ed87124325e75b19d3b2774a48f9504f193206c3"
    privileged: true
    volumes:
      - 'pktfwdr:/var/pktfwd'

  helium-miner:
    image: "nebraltd/hm-miner:e1815721a5d418a78d019705b343fa69854e863d"
    ports:
      - "44158:44158/tcp"
      - "1680:1680/udp"
    volumes:
      - 'miner-storage:/var/data'
      - 'miner-log:/var/log/miner'
      - 'pktfwdr:/var/pktfwd'
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    labels:
      io.balena.features.dbus: '1'
      # io.balena.features.sysfs: '1'
      # io.balena.features.kernel-modules: '1'

  gateway-config:
    image: "nebraltd/hm-config:9055818bfeac9b4725feecb6604bb69f1051f958"
    privileged: true
    network_mode: "host"
    cap_add:
            - NET_ADMIN
    volumes:
      - 'miner-storage:/var/data'
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.sysfs: '1'
      io.balena.features.kernel-modules: '1'
      io.balena.features.supervisor-api: '1'
    stop_signal: SIGINT

  diagnostics:
    image: "nebraltd/hm-diag:50f332085f643da0a0af329afa166ce554f55523"
    volumes:
      - 'pktfwdr:/var/pktfwd'
      - 'miner-storage:/var/data'
    ports:
      - '80:80'
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    labels:
      io.balena.features.sysfs: '1'

  gwmfr:
    image: "nebraltd/hm-gwmfr:8a9473202ecee0b30922677289119ac073686fa5"
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    restart: on-failure

volumes:
  miner-storage:
  miner-log:
  pktfwdr:
