version: '2'

services:

  gateway-config:
    image: "nebraltd/hm-config:f722f1243db45f29d4d589184d61880b98938a82"
    environment:
      - 'FIRMWARE_VERSION=2021.09.27.3'
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
      - 'DBUS_SESSION_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    privileged: true
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - 'miner-storage:/var/data'
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.sysfs: '1'
      io.balena.features.kernel-modules: '1'
    stop_signal: SIGINT

  packet-forwarder:
    image: "nebraltd/hm-pktfwd:a48637d62ea66ab10e3738bf883745b2260fd774"
    privileged: true
    volumes:
      - 'pktfwdr:/var/pktfwd'

  helium-miner:
    image: "nebraltd/hm-miner:a4d8781845b5d9ea262e705e5d44533e5bdfec88"
    expose:
      - "4467"
      - "1680"
    ports:
      - "44158:44158/tcp"
    volumes:
      - 'miner-storage:/var/data'
      - 'miner-log:/var/log/miner'
      - 'pktfwdr:/var/pktfwd'
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
      - 'RELEASE_BUMPER=snapshotbumper'
    labels:
      io.balena.features.dbus: '1'

  diagnostics:
    image: "nebraltd/hm-diag:14a5cf868910c56c465fb9eebd41941ca199106f"
    environment:
      - 'FIRMWARE_VERSION=2021.09.27.3'
    volumes:
      - 'pktfwdr:/var/pktfwd'
      - 'miner-storage:/var/data'
    ports:
      - '80:5000'
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    labels:
      io.balena.features.sysfs: '1'

  gwmfr:
    image: "nebraltd/hm-gwmfr:3a8196239d939fc6d0383a4f39b4fb475c62bad5"
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    restart: on-failure
    volumes:
      - 'miner-storage:/var/data'

  upnp:
    image: "nebraltd/hm-upnp:4e419f5bb5d59b31fcd1f81e0c94f7e94cd9ebee"
    network_mode: "host"
    restart: on-failure
    volumes:
      - 'pktfwdr:/var/pktfwd'

volumes:
  miner-storage:
  miner-log:
  pktfwdr:
