version: '2'

services:
  packet-forwarder:
    image: nebraltd/hm-d-pktfwd:latest
    privileged: true
    volumes:
      - 'pktfwdr:/var/pktfwd'

  helium-miner:
    build: "./miner"
    privileged: true
    ports:
      - "44158:44158/tcp"
      - "1680:1680/udp"
    volumes:
      - 'miner-storage:/var/data'
      - 'miner-log:/var/log/miner'
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.sysfs: '1'
      io.balena.features.kernel-modules: '1'

  gateway-config:
    image: nebraltd/hm-d-gateway-config:latest
    privileged: true
    network_mode: "host"
    cap_add:
            - NET_ADMIN
    volumes:
      - 'miner-storage:/var/data'
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.sysfs: '1'
      io.balena.features.kernel-modules: '1'
      io.balena.features.supervisor-api: '1'
  diagnostics:
    image: nebraltd/hm-d-diagnostics:latest
    privileged: true
    network_mode: "host"
    cap_add:
            - NET_ADMIN
    volumes:
      - 'pktfwdr:/var/pktfwd'



volumes:
  miner-storage:
  miner-log:
  pktfwdr:
