name: Update files in OpenFleets repos

on:
  push:
    paths:
      - "settings.ini"
      - "balena/*"
      - "device-compose-files/*.yml"
  workflow_dispatch:

jobs:
  file-update:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sbc: [rak, pisces, og, sensecap, finestra, controllino, cotx, pantherx1, linxdot, linxdot-rkcm3, pycom, syncrobit, syncrobit-rkcm3, risinghf]
    steps:
      - name: Trigger PR action in helium-${{ matrix.sbc }} repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.MR_BUMP }}
          event-type: file-update
          repository: NebraLtd/helium-${{ matrix.sbc }}
