name: BalenaCloud Deploy (Production - Draft Deploy)

on:
  workflow_dispatch:

jobs:
  build-prod:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sbc: [raspi, rockpi, rak, pisces]
        frequency: [470, 868, 915]
        variant: [indoor, outdoor]
        exclude:
          - sbc: rak
            variant: outdoor
          - sbc: pisces
        include:
          - sbc: pisces
            variant: indoor
            frequency: 868
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: production
      - name: Export short SHA of current commit
        run: |
          FIRMWARE_SHORT_HASH=$( echo ${GITHUB_SHA:0:7} )
          echo "FIRMWARE_SHORT_HASH=$FIRMWARE_SHORT_HASH" >> $GITHUB_ENV
      - name: Random sleep (balena API workaround)
        run:  sleep $[ ( $RANDOM % 360 ) + 1 ]s
      - name: Generate Docker Compose for RockPi
        if: matrix.sbc == 'rockpi'
        run: |
          python gen_docker_compose.py rockpi -o docker-compose.yml
          ROCKPI="-rockpi"
          echo "ROCKPI=$ROCKPI" >> $GITHUB_ENV
      - name: Generate Docker Compose for RaspberryPi & RAK
        if: matrix.sbc == 'raspi' || matrix.sbc == 'rak'
        run: |
          python gen_docker_compose.py rpi -o docker-compose.yml
      - name: Generate Docker Compose for Pisces
        if: matrix.sbc == 'pisces'
        run: |
          python gen_docker_compose.py pisces -o device-compose-files/docker-compose-pisces.yml
          cp device-compose-files/docker-compose-pisces.yml docker-compose.yml
      - name: Balena Deploy (ROCK Pi)
        if: matrix.sbc == 'rockpi' && success()
        uses: nebraltd/balena-cli-action@v13.3.0
        with:
          balena_api_token: ${{secrets.BALENA_API_TOKEN}}
          balena_command: "deploy nebraltd/helium-${{ matrix.variant }}-${{ matrix.frequency }}${{ env.ROCKPI }} --logs --debug --nocache --build --draft"
      - name: Balena Deploy (RasPi)
        if: matrix.sbc == 'raspi' && success()
        uses: nebraltd/balena-cli-action@v13.3.0
        with:
          balena_api_token: ${{secrets.BALENA_API_TOKEN_1}}
          balena_command: "deploy nebraltd/helium-${{ matrix.variant }}-${{ matrix.frequency }} --logs --debug --nocache --build --draft"
      - name: Balena Deploy (RAK)
        if: matrix.sbc == 'rak' && success()
        uses: nebraltd/balena-cli-action@v13.3.0
        with:
          balena_api_token: ${{secrets.BALENA_API_TOKEN_2}}
          balena_command: "deploy nebraltd/helium-${{ matrix.sbc }}-${{ matrix.frequency }} --logs --debug --nocache --build --draft"
      - name: Balena Deploy (Pisces P100)
        if: matrix.sbc == 'pisces' && success()
        uses: nebraltd/balena-cli-action@v13.3.0
        with:
          balena_api_token: ${{secrets.BALENA_API_TOKEN_3}}
          balena_command: "deploy nebraltd/helium-${{ matrix.sbc }} --logs --debug --nocache --build --draft"


  open-fleet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: production
      - name: Export short SHA of current commit
        run: |
          FIRMWARE_SHORT_HASH=$( echo ${GITHUB_SHA:0:7} )
          echo "FIRMWARE_SHORT_HASH=$FIRMWARE_SHORT_HASH" >> $GITHUB_ENV
      - name: Random sleep (balena API workaround)
        run:  sleep $[ ( $RANDOM % 360 ) + 1 ]s
      - name: Generate Docker Compose for RaspberryPi
        run: |
          python gen_docker_compose.py rpi -o docker-compose.yml
      - name: Balena Deploy
        uses: nebraltd/balena-cli-action@v13.3.0
        if: success()
        with:
          balena_api_token: ${{secrets.BALENA_API_TOKEN_2}}
          balena_command: "deploy nebraltd/helium-miner --logs --debug --nocache --build --draft"

  commercial:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: production
      - name: Export short SHA of current commit
        run: |
          FIRMWARE_SHORT_HASH=$( echo ${GITHUB_SHA:0:7} )
          echo "FIRMWARE_SHORT_HASH=$FIRMWARE_SHORT_HASH" >> $GITHUB_ENV
      - name: Random sleep (balena API workaround)
        run:  sleep $[ ( $RANDOM % 360 ) + 1 ]s
      - name: Generate Docker Compose for RaspberryPi
        run: |
          python gen_docker_compose.py rpi -o docker-compose.yml
      - name: Balena Deploy
        uses: nebraltd/balena-cli-action@v13.3.0
        if: success()
        with:
          balena_api_token: ${{secrets.BALENA_API_TOKEN_3}}
          balena_command: "deploy nebraltd/helium-miner-commercial --logs --debug --nocache --build --draft"
