name: BalenaCloud Deploy (Production)

on:
  push:
    # Only run workflow for pushes to specific branches
    branches:
      - production

jobs:
  build-prod:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sbc: [raspi, rockpi]
        frequency: [470, 868, 915]
        variant: [indoor, outdoor]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Docker Compose for RockPi
        if: matrix.sbc == 'rockpi'
        run: |
          python gen_docker_compose.py rockpi -o sample_output/rockpi.yml
          rm docker-compose.yml
          cp sample_output/rockpi.yml docker-compose.yml
          ROCKPI="-rockpi"
          echo "ROCKPI=$ROCKPI" >> $GITHUB_ENV
      - name: Generate Docker Compose for RockPi
        if: matrix.sbc == 'raspi'
        run: |
          python gen_docker_compose.py rpi -o sample_output/rpi.yml
          rm docker-compose.yml
          cp sample_output/rpi.yml docker-compose.yml
      - name: Balena Deploy
        uses: nebraltd/balena-cli-action@v12.54.5
        if: success()
        with:
          balena_api_token: ${{secrets.BALENA_API_TOKEN}}
          balena_command: "deploy nebraltd/helium-${{ matrix.variant }}-${{ matrix.frequency }}${{ env.ROCKPI }} --logs --debug --nocache --build"

  open-fleet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Balena Deploy
        uses: nebraltd/balena-cli-action@v12.54.5
        if: success()
        with:
          balena_api_token: ${{secrets.BALENA_API_TOKEN}}
          balena_command: "deploy nebraltd/helium-miner --logs --debug --nocache --build"

  commercial:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Balena Deploy
        uses: nebraltd/balena-cli-action@v12.54.5
        if: success()
        with:
          balena_api_token: ${{secrets.BALENA_API_TOKEN}}
          balena_command: "deploy nebraltd/helium-miner-commercial --logs --debug --nocache --build"
