name: NebraOS Cloud Deploy (Testnet)

on:
  push:
    # Only run workflow for pushes to specific branches
    branches:
      - master
    paths-ignore:
      - 'device-compose-files/**'
  workflow_dispatch:

jobs:
  testnet:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        variant: [nebra-indoor1, nebra-outdoor1, nebra-indoor2, nebra-outdoor2] # TODO add nebra-light2 later
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python Libraries
        run: pip install -r requirements.txt
      - name: Export short SHA of current commit
        run: |
          FIRMWARE_SHORT_HASH=$( echo ${GITHUB_SHA:0:7} )
          echo "FIRMWARE_SHORT_HASH=$FIRMWARE_SHORT_HASH" >> $GITHUB_ENV
      - name: Random sleep (balena API workaround)
        run:  sleep $[ ( $RANDOM % 60 ) + 1 ]s
      - name: Generate Docker Compose
        run: |
          python gen_docker_compose_by_variant.py ${{matrix.variant}} -o device-compose-files/docker-compose-${{matrix.variant}}.yml
          cp device-compose-files/docker-compose-${{matrix.variant}}.yml docker-compose.yml
      - name: Balena Deploy
        uses: nebraltd/balena-cli-action@v15.0.3-1
        with:
          balena_api_token: ${{secrets.NEBRAOS_CLOUD_TOKEN}}
          nebraos_cloud: true
          balena_command: "deploy nebraltd/testnet-helium-${{matrix.variant}} --debug --nocache --build"
      - name: Push updated docker compose file
        uses: test-room-7/action-update-file@v1
        with:
          branch: master
          file-path: device-compose-files/docker-compose-${{matrix.variant}}.yml
          commit-msg: Update ${{matrix.variant}} variant docker compose output
          github-token: ${{ secrets.MR_BUMP }}
