name: BalenaCloud Deploy (Production)

on:
  push:
    # Only run workflow for pushes to specific branches
    branches:
      - production
env: 
  balena-cli: v12.52.1

jobs:
  build-prod:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sbc: [raspi, rockpi]
        frequency: [470, 868, 915]
        variant: [indoor, outdoor]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Change i2c bus for RockPi
        if: matrix.sbc == 'rockpi'
        run: |
          sed -i -E "s/\/dev\/i2c-1:\/dev\/i2c-1/\/dev\/i2c-7:\/dev\/i2c-7/g" docker-compose.yml
          ROCKPI="-rockpi"
          echo "ROCKPI=$ROCKPI" >> $GITHUB_ENV
      - name: Balena Deploy
        uses: nebraltd/balena-cli-action@${{ env.balena-cli }}
        if: success()
        with:
          balena_api_token: ${{secrets.BALENA_API_TOKEN}}
          balena_command: "deploy nebraltd/helium-${{ matrix.variant }}-${{ matrix.frequency }}${{ env.ROCKPI }} --logs --debug --nocache --build"

  open-fleet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Balena Deploy
        uses: nebraltd/balena-cli-action@${{ env.balena-cli }}
        if: success()
        with:
          balena_api_token: ${{secrets.BALENA_API_TOKEN}}
          balena_command: "deploy nebraltd/helium-miner --logs --debug --nocache --build"

  commercial:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Balena Deploy
        uses: nebraltd/balena-cli-action@${{ env.balena-cli }}
        if: success()
        with:
          balena_api_token: ${{secrets.BALENA_API_TOKEN}}
          balena_command: "deploy nebraltd/helium-miner-commercial --logs --debug --nocache --build"
