name: Ship It!

on:
  push:
    # Only run workflow for pushes to specific branches
    branches:
      - master

jobs:
  helium-indoor-eu868:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1.1.0
    - uses: theaccordance/balena-push@v1.0.0
      with:
        api-token: ${{secrets.BALENA_API_TOKEN}}
        application-name: "HELIUM-INDOOR-EU868"
