name: Test Device Config Generate

on:
  push:
    # Only run workflow for pushes to specific branches
    branches:
      - kashif/use-dot-env-file

jobs:
  testnet:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sbc: [raspi, rockpi]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Docker Compose for RockPi
        if: matrix.sbc == 'rockpi'
        run: |
          python gen_docker_compose.py rockpi -o sample_output/rockpi.yml
          rm docker-compose.yml
          cp sample_output/rockpi.yml docker-compose.yml
          cat docker-compose.yml
          ROCKPI="-rockpi"
          echo "ROCKPI=$ROCKPI" >> $GITHUB_ENV
      - name: Generate Docker Compose for Raspberry Pi
        if: matrix.sbc == 'raspi'
        run: |
          python gen_docker_compose.py rpi -o sample_output/rpi.yml
          rm docker-compose.yml
          cp sample_output/rpi.yml docker-compose.yml
          cat docker-compose.yml
